[package]
name = "rusted"
description = "A simple text editor in Rust"
version = "0.0.1"
edition = "2021"

[dependencies]
#gtk = "0.18.1"
gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git" }
gdk = { git = "https://github.com/gtk-rs/gtk3-rs.git", package = "gdk" }